baseurl = "https://atanasyanew.github.io/blog-tee"
title = "T햇햇"
author = "A. Yanev"
canonifyurls = true
# paginate = 10
theme = "aether-modified"
languageCode = "en-US"
googleAnalytics = "UA-135269393-1"

[params]
brand = "T햇햇"
description = "Theoretical electrical engineering related topics"
#homeimg = "url to the image used for the home button - optional"
#bgimg = "url to the image used for the background - optional" "img/ignasi_pattern_s.png"

# TODO [ay]
# [permalinks]
# posts = "/:year/:month/:title/"
# https://gohugo.io/content-management/urls/#permalinks